### ISSUE TITLE
Do this method still works?

### ISSUE THREAD

**Issue by josephmiller2000** [CodeDotJS/fbvideos#1]
Facebook changed alot in their API for video fetching. Just want to make sure, is this method is still effective?

**Comment by CodeDotJS** [comment]
Hey @josephmiller2000 

> Facebook changed alot in their API for video fetching

This module doesn't depend on Facebook's `API`. It's working absolutely fine. 

I just checked the `api` for the new facebook videos to see if it's working, and yes, it does.

In case, you wanna quick check the functionality, copy and run the following code -

```js
const fb = require('fbvideos');

const url = 'https://www.facebook.com/TypicalIndianComments/videos/931402620380721/'

fb.low(url).then(res => {
  console.log(res);
  // => { url: 'https://video.fdel11-1.fna.fbcdn.net/v/t42.9040-2/32049004_578096759228372_6824419449538347008_n.mp4?_nc_cat=0&efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&oh=ec30eb0cdfa920e6a00ed7ae7658babf&oe=5AF4C9D1' }

});

fb.high(url).then(res => {
  console.log(res);
  // =>  { url: 'https://video.fdel3-1.fna.fbcdn.net/v/t42.9040-2/32200809_1692887157431523_530251869180657664_n.mp4?_nc_cat=0&efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=0e9b14b1d615db670b434f54c9e608d8&oe=5AF4CA1C' }

});
```
Hope this solves your problem!

**Comment by josephmiller2000** [comment]
No idea why I'm getting this error when I tried to install it.
![snap_2018 05 11_02h19m26s_001_](https://user-images.githubusercontent.com/24210340/39893568-c8d2b748-54c1-11e8-8af6-f8077398d017.png)

**Comment by CodeDotJS** [comment]
This conflict happens when the name of the `package` and the name of the `project folder` is same. 

Here, you are trying to install `fbvidoes` as a `dependency` under the `fbvideos` directory which already is a `node package`, so, it's causing this error. 

Just change the directory to something  else, example - (`$ cd ~/Desktop`) and run `$ npm install --save fbvideos` and things will work fine!

**Comment by josephmiller2000** [comment]
Alright i got it :) now it is working.

So is there anyway to make it work in php? So i can make it run in my website to fetch facebook videos in a regular basis.. for an application.

**Comment by CodeDotJS** [comment]
I don't know how you can make it work in PHP, but if know how to code in PHP, I can explain how this `module` works so you can port in the language you like.
